main_home:
    path: /
    controller: App\Controller\MainController::home

main_about:
    path: /about
    controller: App\Controller\MainController::about

movie_list:
    path: /movies
    controller: App\Controller\MovieController::list

movie_show:
    path: /movie
    controller: App\Controller\MovieController::show
